akhq:
  connections:
    local-kafka: 
      properties:
        bootstrap.servers: "localhost:9092"

micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "nIa49TnyBx9rZmm7ywmgr0+Rqcp6DfYDe0BTWAHqI+c="